# f0 extraction settings
dio:
  fs: 16000
  n_fft: 1024
  hop_length: 128
  use_log_f0: True
  num_sub: 4

frontend:
  fs: 16000       # 音声信号のサンプリング周波数．音声認識関連のタスクでは 16kHz が標準的．
  n_fft: 1024     # 短時間フーリエ変換 (STFT) のフレームサイズ．音声認識では512で十分だが，韻律情報の抽出にはより高い解像度が必要．
  hop_length: 128 # フレームの間隔．音声認識では 160 （10ms）が標準的．
  win_length: 800 # フレームの窓幅．音声認識では 400 （25ms）が標準的．
  n_mels: 160     # メルフィルタバンクの数．音声認識では 80 が標準的．

spec_augment:
  time_mask_width_ratio_range:
    - 0.0
    - 0.1
  apply_time_warp: true
  time_warp_window: 5

# data settings
train_wav_scp_filename:      ./dump/raw/train_nodup/wav.scp
train_f0data_dir:            ./f0data/train_nodup/data
train_f0data_scp_filename:   ./f0data/train_nodup/f0data.scp
train_f0data_stats_filename: ./f0data/train_nodup/f0data_stats.txt

val_wav_scp_filename:        ./dump/raw/train_dev/wav.scp
val_f0data_dir:              ./f0data/train_dev/data
val_f0data_scp_filename:     ./f0data/train_dev/f0data.scp
# val_f0data_stats_filename:   ./f0data/train_dev/f0data_stats.txt

# training parameters
batch_size:     20
val_batch_size: 10
num_epochs:     10 # 100
learning_rate:  0.0001

# scheduler parameters (see https://timm.fast.ai/SGDR)
sch_warmup_epochs: 10000 # 25
sch_min_lr: 1e-6
sch_t_initial: 40000 # 70

# device seetings
device: cuda:0

# random seed
random_seed: 42
